### ISSUE TITLE
【严重】（用户门户）用户管理-用户信息维护-添加用户后，没有赋权限，直接登录，报500

### ISSUE THREAD

**Issue by chenhy6** [AIPaaS/PaaS-FE-SYS#1]
@wanwb @zhaolijing1990 
环境win7
浏览器：火狐、Chrome
测试环境：http://10.1.245.247:16004/paas-web
步骤：
1.进入登录页面，租户：test 用户：admin 密码：123456 登录系统
2.用户管理-用户信息维护，添加用户（用户名：chy0304 密码：123456）后，没有赋权限
3.使用（租户：test 用户名：chy0304  密码：123456 ）直接登录，报500
实际结果：
ERROR 500
You do not have permission to access the module '[100] 主页'! 
预期结果：
给出中文提示：没有权限

**Comment by zhaolijing1990** [comment]
@chenhy6  bug已修改，请测试

**Comment by chenhy6** [comment]
通过
