### ISSUE TITLE
【严重】(用户门户)用户管理-用户权限分配-列表中，不应该存在别的租户下的用户

### ISSUE THREAD

**Issue by chenhy6** [AIPaaS/PaaS-FE-SYS#11]
环境win7
浏览器：火狐、Chrome
测试环境：http://10.1.245.247:16004/paas-web
登录-租户：chenhy0304 用户：chenhy 密码：123456
步骤：
1.登录系统
2.用户管理-用户权限分配-查看列表
实际结果：
用户权限分配-列表中，不应该存在别的租户下的用户
预期结果：
1.存在别的租户下的用户
2.数据权限显示问题

**Comment by zhaolijing1990** [comment]
@chenhy6 bug已修改，请测试

**Comment by zhaolijing1990** [comment]
@chenhy6  我们服务器上测试的结果是正常的。
地址：http://10.1.236.126:16004/paas-web/dispatch 
租户：SSS   用户名：admin    密码：123456
代码都是一套，是不是配置文件不同呀？

**Comment by chenhy6** [comment]
问题已解决
