### ISSUE TITLE
【一般】(用户门户)用户管理-角色权限清单-查询一个单独的角色，列表中不应显示所有的菜单

### ISSUE THREAD

**Issue by chenhy6** [AIPaaS/PaaS-FE-SYS#12]
环境win7
浏览器：火狐、Chrome
测试环境：http://10.1.245.247:16004/paas-web
登录-租户：chenhy0304 用户：chenhy 密码：123456
步骤：
1.登录系统
2.用户管理-角色权限清单-（例如：租户管理员）查询
实际结果：
列表显示租户的所有菜单
预期结果：
查询，单独的一个角色，应只显示此角色的菜单

**Comment by oriiro** [comment]
bug 已修改完 请重新测试

**Comment by chenhy6** [comment]
通过
