### ISSUE TITLE
【一般】（用户门户）租户注册申请-电话号码项，没有校验

### ISSUE THREAD

**Issue by chenhy6** [AIPaaS/PaaS-FE-SYS#14]
环境win7
浏览器：火狐、Chrome
测试环境：http://10.1.245.247:16004/paas-web
步骤：
1.进入登录页面
2.点击 租户注册申请，进入注册页面，电话号码 项
实际结果：
电话号码项 没有校验，可以输入如何字符
预期结果：
只允许输入数字（ 11位手机号码和座机号码）

@wanwb @renfeng3

**Comment by jiasx** [comment]
已经处理

**Comment by chenhy6** [comment]
问题未解决

**Comment by jiasx** [comment]
已经处理

**Comment by chenhy6** [comment]
通过
