### ISSUE TITLE
[一般]（用户门户）租户注册申请页面，不应有验证码（如图）

### ISSUE THREAD

**Issue by chenhy6** [AIPaaS/PaaS-FE-SYS#16]
环境：win7
浏览器：火狐、Chrome
测试环境：http://10.1.245.247:16004/paas-web
步骤：
1.进入登录页面，点击“注册申请”按钮，进入租户注册申请页面
实际结果：
出现 验证码
预期结果：
注册页面，不需要 验证码

**Comment by mapl-pisces** [comment]
已经去除验证码

**Comment by chenhy6** [comment]
通过
