### ISSUE TITLE
[一般]（用户门户）用户管理-用户信息维护-添加/修改-手机号，没有校验

### ISSUE THREAD

**Issue by chenhy6** [AIPaaS/PaaS-FE-SYS#17]
环境：win7
浏览器：火狐、Chrome
测试环境：http://10.1.245.247:16004/paas-web
登录-租户：chenhy0304 用户：chenhy 密码：123456
步骤：
1.登录系统
2.用户管理-用户信息维护-添加/修改-手机号
实际结果：
手机号 没有校验，可以输入任何字符
预期结果：
只允许 输入数字（手机号11位）

**Comment by jiasx** [comment]
添加/修改手机号已经做验证，只允许 输入数字（手机号11位）。并内测。

**Comment by chenhy6** [comment]
问题没解决

**Comment by jiasx** [comment]
问题已经处理

**Comment by chenhy6** [comment]
通过
