### ISSUE TITLE
[一般]（用户门户）用户管理-角色权限清单-角色-查询-下拉框-列表 显示全部信息的选项，显示空白，建议：添上“全部“

### ISSUE THREAD

**Issue by chenhy6** [AIPaaS/PaaS-FE-SYS#18]
环境：win7
浏览器：火狐、Chrome
测试环境：http://10.1.245.247:16004/paas-web
登录-租户：chenhy0304 用户：chenhy 密码：123456
步骤：
1.登录系统
2.用户管理-角色权限清单-查询-下拉框-列表 显示全部信息的选项
实际结果：
显示全部信息的选项，显示空白
预期结果：
建议：添上“全部“字样

**Comment by oriiro** [comment]
bug已修改完 请重新测试

**Comment by chenhy6** [comment]
通过
