### ISSUE TITLE
[一般]（用户门户）用户管理-用户信息维护，添加一个已存在的用户，点击“保存”，提示“is exists code chy0304”,

### ISSUE THREAD

**Issue by chenhy6** [AIPaaS/PaaS-FE-SYS#19]
环境：win7
浏览器：火狐、Chrome
测试环境：http://10.1.245.248:16002/paas-console
登录-用户：chy 密码：123456
步骤：
1.登录系统
2.用户管理-用户信息维护，添加一个已存在的用户代码/用户姓名，点击“保存”，
实际结果：
提示“is exists code chy0304”,
预期结果：
给出中文提示：用户已存在

**Comment by zhaolijing1990** [comment]
@chenhy6 修改完毕，可以测试了。

**Comment by chenhy6** [comment]
问题还存在

**Comment by zhaolijing1990** [comment]
@chenhy6  bug修改完毕，请测试

**Comment by chenhy6** [comment]
验证通过
