### ISSUE TITLE
【一般】（管理门户）系统管理-前/后台权限-用户角色/角色资源分配-列表，勾选列表中的"全选"按钮，不起作用。

### ISSUE THREAD

**Issue by chenhy6** [AIPaaS/PaaS-FE-SYS#2]
环境win7
浏览器：火狐、Chrome
测试环境：
管理门户：http://10.1.245.248:16002/paas-console
步骤：
1.登录系统；
2.进入系统管理-前/后台权限-用户角色/角色资源分配-列表，勾选列表中的"全选"按钮，不起作用。
实际结果：
目前只勾选了最后一条数据
预期结果：
勾选 “全选”按钮，全部数据自动勾选上

**Comment by renfeng3** [comment]
@chenhy6 讨论决定此问题不做修改

**Comment by chenhy6** [comment]
通过
