### ISSUE TITLE
[一般]（用户门户）租户注册申请-租户名称，输入框，输入中文名称 之外的字符，没有提示（没有校验）

### ISSUE THREAD

**Issue by chenhy6** [AIPaaS/PaaS-FE-SYS#20]
环境：win7
浏览器：火狐、Chrome
测试环境：http://10.1.245.247:16004/paas-web
步骤：
1.正常登录页面
2.租户注册申请-租户名称，输入框，输入中文名称 之外的字符
实际结果：
没有提示
预期结果：
请校验，输入中文名称 之外的字符，提示 请与要求的格式保持一致

**Comment by jiasx** [comment]
租户注册申请-租户名称，输入框已经做验证：  
代码：pattern="[\u4e00-\u9fa5]"

**Comment by chenhy6** [comment]
问题没解决

**Comment by chenhy6** [comment]
重新更新代码后，验证通过
