### ISSUE TITLE
(用户门户)租户注册申请-登录密码项，没有校验

### ISSUE THREAD

**Issue by chenhy6** [AIPaaS/PaaS-FE-SYS#21]
环境：win7
浏览器：火狐、Chrome
测试环境：http://10.1.245.247:16004/paas-web
                 http://10.1.245.248:16002/paas-console
步骤：
1.进入系统登录页
2.点击“注册申请”，进入租户注册页
3.填写所有信息正确，租户代码：chenhy0307  登录密码：12345678900987654321
4.管理门户（登录-用户：chy 密码：123456），租户注册审批后，使用租户：chenhy0307 登录
实际结果：
提示 密码不对
预期结果：
注册时密码，允许输入（6-16位），但 实际输入12345678900987654321，能保存成功，登录时确提示错误，请校验

**Comment by zhaolijing1990** [comment]
@chenhy6 租户注册时，虽然你的密码输入的是：12345678900987654321。但是，实际上，输入框限制了密码的长度，最多为16位。所以密码保存时，只保存了前16位。即：1234567890098765。
说白了就是，你用1234567890098765作为密码，就能进去了。

**Comment by jiasx** [comment]
现在租户注册页面的 "登录密码、密码确认"输入框密码字符是做限制的。
代码如下：maxlength="16" pattern=".{6,16}"  用浏览器内测了，没有出现这个问题。
有问题再沟通。

**Comment by chenhy6** [comment]
问题已解决
