### ISSUE TITLE
(用户门户)新建用户-未赋权限，直接登录，提示用户名错误

### ISSUE THREAD

**Issue by chenhy6** [AIPaaS/PaaS-FE-SYS#22]
环境：win7
浏览器：火狐、Chrome
测试环境：http://10.1.245.247:16004/paas-web
登录-租户：chenhy0304 用户：admin 密码：123456
步骤：
1.登录系统
2.在 用户管理-用户信息维护，新建用户chy0304成功
3.在登录页面，输入租户：chenhy0304 ，用户：chy0304 密码：123456
4.点击“登录”
实际结果：
提示 用户名错误
预期结果：
提示 此用户未赋权限
备注：个人认为，用户未赋权限的情况下，应该可以登录，看到主页面

**Comment by zhaolijing1990** [comment]
@chenhy6 目前效果为。新用户未赋权限，直接登录，显示“该用户没有权限[100] 主页!，此外，还有2个链接地址“返回“” 重新登录”

**Comment by chenhy6** [comment]
通过
