### ISSUE TITLE
[一般]（用户门户）用户管理-用户权限分配-列表信息，没有排序

### ISSUE THREAD

**Issue by chenhy6** [AIPaaS/PaaS-FE-SYS#23]
环境：win7
浏览器：火狐、Chrome
测试环境：http://10.1.245.247:16004/paas-web
登录-租户：chenhy0304 用户：chenhy 密码：123456
步骤：
1.登录系统
2.用户管理-用户权限分配-列表，查看列表数据
实际结果：
新建用户，在中间位置
预期结果：
新建用户，排在第一位

**Comment by zhaolijing1990** [comment]
@chenhy6 已经修改好了

**Comment by chenhy6** [comment]
用户管理-用户信息维护-列表，查看列表数据 有同样问题，请修改

**Comment by zhaolijing1990** [comment]
@chenhy6  bug修改完毕，请测试

**Comment by chenhy6** [comment]
通过
