### ISSUE TITLE
[一般]（用户门户）用户管理-用户注销，用户注销成功后，再登录，提示“用户名输入错误”，用户体验不好，建议改成：此用户已被注销

### ISSUE THREAD

**Issue by chenhy6** [AIPaaS/PaaS-FE-SYS#24]
环境：win7
浏览器：火狐、Chrome
测试环境：http://10.1.245.247:16004/paas-web
登录-租户：chenhy0304 用户：qq22 密码：1234567890

用户管理-用户注销，用户注销成功后，再登录，提示“用户名输入错误”
个人认为：用户体验不好
建议改成：此用户已被注销

**Comment by oriiro** [comment]
bug已改完 请重新测试

**Comment by chenhy6** [comment]
验证通过
