### ISSUE TITLE
【一般】（用户门户）系统长时间不操作，再操作时，提示 出现错误：must be login

### ISSUE THREAD

**Issue by chenhy6** [AIPaaS/PaaS-FE-SYS#28]
环境：win7
浏览器：火狐、Chrome
测试环境：http://10.1.245.247:16004/paas-web
登录-租户：chenhy0304 用户：chenhy 密码：123456
步骤：
1.登录系统
2.系统长时间不操作，再操作时，提示 出现错误：must be login
实际结果：
提示 出现错误：must be login
预期结果：
系统中不应出现英文提示，建议提示 请重新登录或直接返回登录页面

**Comment by mapl-pisces** [comment]
1）、提测的功能说明： 登录超时提示修改为：页面已超时，请重新登录！
2）、代码分支说明：所有项目的develop 分支
3）、配置信息说明：无
4）、数据库说明：无
5）、是否有特殊的第三方软件安装：无

**Comment by chenhy6** [comment]
验证通过
