### ISSUE TITLE
【一般】（用户门户）用户管理-用户信息维护-选择用户修改，不修改任何信息，直接点“提交”，提示请输入密码，原密码没带出来。

### ISSUE THREAD

**Issue by chenhy6** [AIPaaS/PaaS-FE-SYS#29]
环境：win7
浏览器：火狐、Chrome
测试环境：http://10.1.245.247:16004/paas-web
登录-租户：chenhy0304 用户：chenhy 密码：123456
步骤：
1.登录系统
2.用户管理-用户信息维护-选择用户修改，不修改任何信息，直接点“提交”
实际结果：提示请输入密码
预期结果：保存成功，密码还是原来的

**Comment by mapl-pisces** [comment]
1）、提测的功能说明：用户管理-用户信息维护-选择用户修改，不修改任何信息，直接点“提交”，可以通过
2）、代码分支说明：所有的项目都需要重新构建  develop 分支
3）、配置信息说明：无
4）、数据库说明：update sys_op set LOGIN_PASSWD = '7463bd4088bcf044b20db19e7c3e0ee7' ;
        执行后，所有的用户密码都被初始化为：123456。 
5）、是否有特殊的第三方软件安装：无

**Comment by chenhy6** [comment]
验证通过
