### ISSUE TITLE
[一般]用户管理-用户权限分配列表，分配权限失败

### ISSUE THREAD

**Issue by xiexm** [AIPaaS/PaaS-FE-SYS#3]
@wanwb @zhaolijing1990 
[概要]：[用户门户]用户管理-用户权限分配列表，分配权限失败
[详细步骤]：
1.租户用户A登录成功后
2.用户管理-用户权限分配列表，选择用户（user1）一条数据，点击【分配角色】按钮
3.在弹出的窗口，勾选相应角色，如：工程管理员，点击确定按钮
4.分配权限失败，此问题由于数据权限问题导致。（用户usr1不属于租户A下的用户)
[实际结果]：
点击确定按钮，分配权限失败，弹出提示：you don't have permission to change user[188] information
[预期结果]:
分配权限成功，界面数据显示正常
[重现率]:100%
[bug严重程度]:一般

**Comment by oriiro** [comment]
user1不属于租户A下的用户 怎么会能分配权限呢。 @xiexm

**Comment by xiexm** [comment]
数据权限问题导致，目前用户权限分配列表数据显示正常，以上问题已不存在，正常关闭。
