### ISSUE TITLE
[一般]（用户门户）登录页-租户申请注册，页面多了个“登录”按钮，预期结果：只需要一个 “注册”按钮

### ISSUE THREAD

**Issue by chenhy6** [AIPaaS/PaaS-FE-SYS#30]
环境：win7
浏览器：火狐、Chrome
测试环境：http://10.1.245.247:16004/paas-web
步骤：
1、进入登录页
2、点击  申请注册，进入租户申请注册页
实际结果：
页面多了个“登录”按钮
预期结果：只需要一个 “注册”按钮

**Comment by mapl-pisces** [comment]
1）、提测的功能说明：租户注册页面去除登录按钮
2）、代码分支说明：https://github.com/AIPaaS/PaaS-FE-SSO.git   develop
3）、配置信息说明：无
4）、数据库说明：无
5）、是否有特殊的第三方软件安装：无

**Comment by chenhy6** [comment]
验证通过
