### ISSUE TITLE
[一般]（管理门户）登录界面，登录名、密码、验证码， 输入框内，无提示（浏览器IE9不兼容）

### ISSUE THREAD

**Issue by chenhy6** [AIPaaS/PaaS-FE-SYS#32]
环境：win7
浏览器：IE9
测试环境：http://10.1.245.248:16002/paas-console
登录-用户：chy 密码：123456
步骤：
登录界面，登录名、密码、验证码， 输入框
实际结果：
输入框内，无提示
预期结果：
登录名、密码、验证码， 输入框 显示提示字符（浏览器IE9不兼容）

**Comment by guohong1** [comment]
在输入框添加了title，鼠标放上就可以看到

**Comment by chenhy6** [comment]
验证通过
