### ISSUE TITLE
[一般]（用户门户）登录界面及租户注册申请页面，所有的 输入框内，都无提示（浏览器IE9不兼容）

### ISSUE THREAD

**Issue by chenhy6** [AIPaaS/PaaS-FE-SYS#33]
环境：win7
浏览器：IE9
测试环境：http://10.1.245.247:16004/paas-web
1.进入登录页面
2.查看登录输入框，登录名、密码、验证码， 输入框内，无提示（浏览器IE9不兼容）
3.点击进入租户申请注册页，查看输入框，所有的输入框都无提示（浏览器IE9不兼容）
预期结果：
输入框内，有字符内容提示

**Comment by guohong1** [comment]
在每个输入框加了一个title，把鼠标放上去就可以看到

**Comment by chenhy6** [comment]
验证通过
