### ISSUE TITLE
【严重】用户门户链接地址，在IE11、360-7.1版上都不能打开（浏览器不兼容）

### ISSUE THREAD

**Issue by chenhy6** [AIPaaS/PaaS-FE-SYS#34]
环境：win7
浏览器：IE9、360 7.1版
测试环境：http://10.1.245.247:16004/paas-web

用户门户链接地址，在IE11、360-7.1版上都不能打开（浏览器不兼容）

**Comment by mapl-pisces** [comment]
测试已关闭
