### ISSUE TITLE
[一般]用户管理-用户权限分配，点击分配权限按钮后，在弹出的对话框标题栏字体被遮盖

### ISSUE THREAD

**Issue by xiexm** [AIPaaS/PaaS-FE-SYS#4]
@wanwb @zhaolijing1990 
[概要]：用户管理-用户权限分配，点击分配权限按钮后，在弹出的对话框标题栏字体被遮盖
[详细步骤]：
1.【用户门户】租用管理员xie登录，
2. 用户管理-用户权限分配，选择第一条用户数据，点击【分配权限】按钮后，在弹出的对话框中标题栏字体被遮盖。
[实际结果]：
标题栏字体被遮盖
[预期结果]:
标题栏字体正常显示
[重现率]:100%
![Uploading 字体遮盖.gif…]()

**Comment by jiasx** [comment]
问题已经处理，并内测可以正常访问。

**Comment by xiexm** [comment]
验证通过。
