### ISSUE TITLE
[一般]用户管理-用户信息界面，字段(手机号，邮箱)未做校验

### ISSUE THREAD

**Issue by xiexm** [AIPaaS/PaaS-FE-SYS#5]
@wanwb @zhaolijing1990 
[概要]：[一般]用户管理-用户信息界面，手机号和邮箱未做校验
[详细步骤]：
1.【用户门户】租用管理员0301登录，用户管理-用户信息维护，添加界面，手机号码未校验，输入汉字或特殊字符可以保存成功。                          
 2.【用户门户】租用管理员0301登录，用户管理-用户信息维护，添加界面，邮箱地址校验不正确，如，输入xie@11111111可以保存成功
[实际结果]：
手机号和邮箱未做校验
[预期结果]:
手机号和邮箱做正确校验。
[重现率]:100%

**Comment by jiasx** [comment]
手机号，邮箱已经做验证。并内测，可以正常显示。
邮箱：   <input type="mail" required/>
手机号:  <input type="text" pattern="(\d{11})|^((\d{7,8})|(\d{4}|\d{3})-(\d{7,8})|(\d{4}|\d{3})-(\d{7,8})-(\d{4}|\d{3}|\d{2}|\d{1})|(\d{7,8})-(\d{4}|\d{3}|\d{2}|\d{1}))$" required="required"/>

**Comment by xiexm** [comment]
验证通过。
