### ISSUE TITLE
【一般】chrome48浏览器下，登录界面申请注册按钮分两行显示

### ISSUE THREAD

**Issue by xiexm** [AIPaaS/PaaS-FE-SYS#7]
测试环境：
用户门户：http://10.1.245.247:16004/paas-web
[概要]：
[详细步骤]：
1.chrome48浏览器下，用户门户登录界面【申请注册】链接分两行显示
[实际结果]
申请注册链接分两行显示
[预期结果]:
申请注册一行显示
[重现率]:100%
@wanwb @zhaolijing1990

**Comment by jiasx** [comment]
字体问题，已经做调整。并内测，可以正常显示

**Comment by xiexm** [comment]
验证通过。
