### ISSUE TITLE
[一般]注册租户时，输入超长字符时，点击注册按钮，界面报错

### ISSUE THREAD

**Issue by xiexm** [AIPaaS/PaaS-FE-SYS#8]
环境win7
浏览器：火狐
测试环境：
用户门户：http://10.1.245.247:16004/paas-web
[概要]：注册租户时，输入超长字符时，点击注册按钮，界面报错
[详细步骤]：
1.用户门户登录界面，点击申请注册
2.注册界面，各个字段中输入超长字符时，点击注册按钮，提示：call remote service 'MerchentSvc.saveOrUpdate()' error! Null
[实际结果]：
输入超长字符串时，点击注册按钮，界面报错
[预期结果]:
建议：
1.输入超长字符串时，给出友好提示信息
2.做最大长度限制，超过最大值时不能输入。
[重现率]:100%
[版本号]:

**Comment by jiasx** [comment]
字体设置问题，已经解决

**Comment by jiasx** [comment]
1.输入超长字符串时，给出友好提示信息
2.做最大长度限制，超过最大值时不能输入。
已经做限制。并内测

**Comment by xiexm** [comment]
验证通过。
