### ISSUE TITLE
【一般】（用户门户）用户管理-用户信息维护－修改用户信息时，查看原先设置的登录密码没显示

### ISSUE THREAD

**Issue by chenhy6** [AIPaaS/PaaS-FE-SYS#9]
环境win7
浏览器：火狐、Chrome
测试环境：http://10.1.245.247:16004/paas-web
登录：租户名：chy 用户名：admin 密码：123456
步骤：
1.登录系统
2.（用户门户）用户管理-用户信息维护－修改用户信息时
3.查看密码输入框
实际结果：
原先设置的登录密码没显示
预期结果：
密文显示或明文显示 密码

**Comment by zhaolijing1990** [comment]
@chenhy6 修改用户信息时，不需要显示旧密码吧？
一般都是，先输入旧密码，用于验证。然后输入两遍新密码。

**Comment by chenhy6** [comment]
@zhaolijing1990 
修改用户信息时，网页版 一般情况 旧密码 都以密文形式显示

**Comment by chenhy6** [comment]
不改也可以
